export const SAVE_USER = 'SAVE_USER'
export const REMOVE_USER = 'REMOVE_USER'
export const ADD_INCOME = 'ADD_INCOME'
export const ADD_EXPENSE = 'ADD_EXPENSE'
export const DELETE_INCOME = 'DELETE_INCOME'
export const DELETE_EXPENSE = 'DELETE_EXPENSE'
export const SET_LIFF_DATA = 'SET_LIFF_DATA'